name: Print Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Hello World
      uses: docker://python:3.9
      with:
        entrypoint: python
        args: -c "print('Hello, World!')"
