name: Build and Run Python Container

on:
  push:
    branches:
      - main

jobs:
  build-python-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use

      - name: Build Python Docker Image
        run: docker build -t my-python-app .

      - name: Run Python Docker Container
        run: docker run --name my-python-container my-python-app
